

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace snglrtycrvtureofspce.Hotels.Desktop.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class KingWilliamHotelDBEntities3 : DbContext
{
    public KingWilliamHotelDBEntities3()
        : base("name=KingWilliamHotelDBEntities3")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tblGuests> tblGuests { get; set; }

    public virtual DbSet<tblReservations> tblReservations { get; set; }

    public virtual DbSet<tblRooms> tblRooms { get; set; }

}

}

