
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace snglrtycrvtureofspce.Hotels.Desktop.Model
{

using System;
    using System.Collections.Generic;
    
public partial class tblGuests
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblGuests()
    {

        this.tblReservations = new HashSet<tblReservations>();

    }


    public string GuestID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string GuestAddress { get; set; }

    public string Gender { get; set; }

    public string Phone { get; set; }

    public string EmailAddress { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblReservations> tblReservations { get; set; }

}

}
