
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace snglrtycrvtureofspce.Hotels.Desktop.Model
{

using System;
    using System.Collections.Generic;
    
public partial class tblReservations
{

    public int ReservationID { get; set; }

    public string GuestID { get; set; }

    public string RoomID { get; set; }

    public string EmployeeID { get; set; }

    public System.DateTime DateMade { get; set; }

    public System.DateTime ReservationStartDate { get; set; }

    public System.DateTime ReservationEndDate { get; set; }



    public virtual tblGuests tblGuests { get; set; }

    public virtual tblRooms tblRooms { get; set; }

}

}
