//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace snglrtycrvtureofspce.Hotels.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\\\SNGLRTYCRVTUREO,1433;Initial Catalog=LostAnimalsDesktop-Se" +
            "rvice;User Id=sa;password=TbAlu5ZE2Y8l;MultipleActiveResultSets=true;TrustServer" +
            "Certificate=True")]
        public string connectionString {
            get {
                return ((string)(this["connectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\KingWilliamHo" +
            "telDB.mdf;Integrated Security=True;Connect Timeout=30")]
        public string KingWilliamHotelDBConnectionString1 {
            get {
                return ((string)(this["KingWilliamHotelDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-078D6KH;Initial Catalog=\"D:\\GOOGLE DRIVE\\MY COMPUTER\\DURHAM\\S" +
            "EM 5\\DBAS\\DEL 4\\APPLICATION\\KINGWILLIAMHOTELDB.MDF\";Integrated Security=True")]
        public string D__GOOGLE_DRIVE_MY_COMPUTER_DURHAM_SEM_5_DBAS_DEL_4_APPLICATION_KINGWILLIAMHOTELDB_MDFConnectionString {
            get {
                return ((string)(this["D__GOOGLE_DRIVE_MY_COMPUTER_DURHAM_SEM_5_DBAS_DEL_4_APPLICATION_KINGWILLIAMHOTELD" +
                    "B_MDFConnectionString"]));
            }
        }
    }
}
